FROM python:3.10-slim

WORKDIR /app

COPY streamlit_app.py .

RUN pip install --no-cache-dir streamlit pandas requests matplotlib

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.enableCORS=false", "--server.address=0.0.0.0"]
