FROM python:3.10-slim

RUN pip install --no-cache-dir mlflow==2.11.1 gunicorn

EXPOSE 5000

CMD mlflow server \
    --backend-store-uri sqlite:///mlflow.db \
    --default-artifact-root /mlruns \
    --host 0.0.0.0 \
    --port 5000
